//#![deny(missing_docs)]
//#![doc = include_str!("../readme.md")]

pub mod averages;
pub mod bytes;
pub mod color;
pub mod command;
pub mod env;
pub mod experience;
pub mod fimfiction_api;
pub mod fs;
pub mod hash;
pub mod http;
pub mod json;
pub mod log;
pub mod markdown;
pub mod number_format;
pub mod pagination;
pub mod passphrase;
pub mod regex;
pub mod smart_map;
pub mod sprite_sheet;
pub mod stderr;
pub mod stdin;
pub mod string_image;
pub mod structs;
pub mod threads;
pub mod time;
pub mod traits;
pub mod word_stats;
