[package]
name = "fluttershy"
version = "0.1.0"
description = "Error handling library."
homepage = "https://github.com/SilkRose/Pony/tree/mane/code/packages/fluttershy"

repository = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
