[package]
name = "rarity"
version = "0.3.0"
description = "Library for counting word occurances in a string, and deriving statistics from it."
homepage = "https://github.com/SilkRose/Pony/tree/mane/code/packages/rarity"

repository = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
regex = { workspace = true }
serde = { workspace = true }
