[package]
name = "rarity"
version = "0.1.0"
description = "CLI tools and library for various uses in the Pony repo."
repository = "https://github.com/SilkRose/Pony"
homepage = "https://github.com/SilkRose/Pony/tree/mane/code/"
authors = ["Silk Rose", "Meadowsys"]
edition = "2021"
license = "CC0-1.0"
readme = "./README.md"

[workspace.package]
authors = ["Silk Rose", "Meadowsys"]
edition = "2021"
license = "CC0-1.0"
repository = "https://github.com/SilkRose/Pony"

[dependencies]
camino = { version = "1.1.6" }
regex = { version = "1.10.2" }

[workspace.dependencies]
atty = "0.2.14"
camino = { version = "1.1.6" }
crossterm = { version = "0.27.0" }
markdown = { version = "1.0.0-alpha.16" }

[workspace]
resolver = "2"
members = [
	"fim",
	"fimdoc"
]

[profile.dev]
opt-level = 0
debug-assertions = true
debug = true
incremental = true

[profile.release]
strip = true
opt-level = 3
debug-assertions = false
lto = true
codegen-units = 1
