[package]
name = "pony"
version = "0.0.0"
description = "Binaries for the Pony repo."
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[workspace.package]
authors = ["Silk Rose", "Meadowsys"]
edition = "2021"
license = "MIT"
repository = "https://github.com/SilkRose/Pony"

[dependencies]
camino = { workspace = true }
fimdoc = { path = "./packages/fimdoc" }
fluttershy = { path = "./packages/fluttershy" }
rayon = { version = "1.10.0" }
regex = { workspace = true }

[workspace.dependencies]
atty = { version = "0.2.14" }
camino = { version = "1.1.6" }
indoc = { version = "2.0.5" }
markdown = { version = "1.0.0-alpha.16" }
num_cpus = {version = "1.16.0" }
pinkie-pie = { path = "./packages/pinkie-pie", version = "0.1.0" }
regex = { version = "1.10.4" }
serde = { version = "1", features = ["derive"] }
terminal_color_builder = { version = "0.1.1" }

[workspace]
resolver = "2"
members = [
	"packages/fimdoc",
	"packages/fluttershy",
	"packages/golden-oak-library",
	"packages/pinkie-pie",
	"packages/rainbow-dash",
	"packages/rarity"
]

[profile.dev]
opt-level = 0
debug-assertions = true
debug = true
incremental = true

[profile.release]
strip = true
opt-level = 3
debug-assertions = false
lto = true
codegen-units = 1
