[package]
name = "pony"
version = "0.0.0"
description = "CLI tools and library for various uses in the Pony repo."
repository = "https://github.com/SilkRose/Pony"
authors = ["Silk Rose", "Meadowsys"]
edition = "2021"
license = "CC0-1.0"
publish = false

[dependencies]
async-recursion = "1.0.5"
atty = { version = "0.2.14" }
camino = { version = "1.1.6" }
lazy_static = { version = "1.4.0" }
markdown = { version = "1.0.0-alpha.16" }
regex = { version = "1.10.3" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["preserve_order"] }
terminal_color_builder = { version = "0.1.1" }
tokio = { version = "1", features = ["full"] }
wiwi = { version = "0.3.1", features = ["clock-timer-2", "tokio"] }

[profile.dev]
opt-level = 0
debug-assertions = true
debug = true
incremental = true

[profile.release]
strip = true
opt-level = 3
debug-assertions = false
lto = true
codegen-units = 1
