[package]
name = "pony"
version = "0.0.0"
description = "Binaries for the Pony repo."
publish = false
authors = ["Silk Rose", "Meadowsys"]
edition = "2024"
license = "MIT"
repository = "https://github.com/SilkRose/Pony"

[dependencies]
blake3 = { version = "1.8.3" }
camino = { version = "1.2.2" }
chrono = { version = "0.4.44" }
chrono-tz = { version = "0.10.4" }
git2 = { version = "0.20.4" }
image = { version = "0.25.9" }
indoc = { version = "2.0.7" }
markdown = { version = "1.0.0" }
num_cpus = { version = "1.17.0" }
rand = { version = "0.10.0" }
regex = { version = "1.12.3" }
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
sha2 = { version = "0.10.9" }
tokio = { version = "1.49.0" }

[profile.dev]
opt-level = 0
debug-assertions = true
debug = true
incremental = true

[profile.release]
strip = true
opt-level = 3
debug-assertions = false
lto = true
codegen-units = 1
