[package]
name = "golden-oak-library"
version = "0.1.0"
description = "CLI tools and library for various uses in the Pony repo."
#readme = "./readme.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[workspace.package]
authors = ["Silk Rose", "Meadowsys"]
edition = "2021"
license = "MIT"
repository = "https://github.com/SilkRose/Pony"

[dependencies]
#async-recursion = "1.1.0"
atty = { version = "0.2.14" }
camino = { workspace = true }
fimdoc = { path = "./packages/fimdoc" }
#lazy_static = { version = "1.4.0" }
rayon = { version = "1.10.0" }
regex = { workspace = true }
#reqwest = { version = "0.12", features = ["json"] }
#serde = { workspace = true }
#serde_json = { version = "1", features = ["preserve_order"] }
terminal_color_builder = { version = "0.1.1" }
#tokio = { version = "1", features = ["full"] }
#wiwi = { version = "0.5.3", features = ["clock-timer-2", "tokio"] }

[workspace.dependencies]
camino = { version = "1.1.6" }
golden-oak-library = { path = "./", version = "0.1.0" }
indoc = { version = "2.0.5" }
markdown = { version = "1.0.0-alpha.16" }
regex = { version = "1.10.4" }
serde = { version = "1", features = ["derive"] }

[workspace]
resolver = "2"
members = [
	"packages/fimdoc",
	"packages/rarity"
]

[profile.dev]
opt-level = 0
debug-assertions = true
debug = true
incremental = true

[profile.release]
strip = true
opt-level = 3
debug-assertions = false
lto = true
codegen-units = 1
