[package]
name = "pony"
version = "0.0.0"
description = "Binaries for the Pony repo."
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[workspace.package]
authors = ["Silk Rose", "Meadowsys"]
edition = "2021"
license = "MIT"
repository = "https://github.com/SilkRose/Pony"

[dependencies]
atty = { version = "0.2.14" }
camino = { workspace = true }
fancy-regex = { version = "0.13.0" }
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_6"] }
indoc = { workspace = true }
markdown = { workspace = true }
num_cpus = {version = "1.16.0" }
rayon = { version = "1.10.0" }
regex = { version = "1.10.4" }
serde = { version = "1", features = ["derive"] }
sha2 = { version = "0.10.8" }
terminal_color_builder = { version = "0.1.1" }

fimdoc = { path = "./packages/fimdoc" }

[workspace.dependencies]
camino = { version = "1.1.6" }
indoc = { version = "2.0.5" }
markdown = { version = "1.0.0-alpha.17" }

[workspace]
resolver = "2"
members = [
	"packages/fanfic",
	"packages/fanfic-macros",
	"packages/fimdoc"
]

[profile.dev]
opt-level = 0
debug-assertions = true
debug = true
incremental = true

[profile.release]
strip = true
opt-level = 3
debug-assertions = false
lto = true
codegen-units = 1
