[package]
name = "pony"
version = "0.0.0"
description = "Binaries for the Pony repo."
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[workspace.package]
authors = ["Silk Rose", "Meadowsys"]
edition = "2021"
license = "MIT"
repository = "https://github.com/SilkRose/Pony"

[dependencies]
atty = { version = "0.2.14" }
camino = { workspace = true }
git2 = { version = "0.19.0" }
indoc = { version = "2.0.5" }
markdown = { version = "1.0.0-alpha.18" }
regex = { workspace = true }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.121", features = ["preserve_order"] }
terminal_color_builder = { version = "0.1.1" }
thiserror = { version = "1.0.63" }

[workspace.dependencies]
camino = { version = "1.1.7" }
proc-macro2 = { version = "1.0.86" }
quote = { version = "1.0.36" }
regex = { version = "1.10.5" }
syn = { version = "2.0.72" }

[workspace]
members = ["packages/fanfic", "packages/fanfic-macros"]

[profile.dev]
opt-level = 0
debug-assertions = true
debug = true
incremental = true

[profile.release]
strip = true
opt-level = 3
debug-assertions = false
lto = true
codegen-units = 1
