[package]
name = "fimdoc"
version = "0.6.1"
description = "Firendship is Magic Document, converts Markdown into FIMFiction BBCode."
readme = "./readme.md"

repository = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
camino = { workspace = true }
indoc = { workspace = true }
markdown = { workspace = true }
golden-oak-library = { version = "0.1.0" }
