[package]
name = "golden-oak-library"
version = "0.2.0"
description = "Library of usefull functions."
homepage = "https://github.com/SilkRose/Pony/tree/mane/code/packages/golden-oak-library"
readme = "./readme.md"

repository = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
num_cpus = { workspace= true }
serde = { workspace = true }
