[package]
name = "trot"
version = "0.1.1"
description = "Trait library."
keywords = ["trait", "traits"]
homepage = "https://github.com/SilkRose/Pony/tree/mane/code/packages/trot"
readme = "./readme.md"

repository = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
