[package]
name = "rainbow-dash"
version = "0.0.0"
description = "To be determined."
homepage = "https://github.com/SilkRose/Pony/tree/mane/code/packages/rainbow-dash"

repository = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
