name: Binary Rebuild Check

on:
  push:
    branches:
    # - mane
    - disabled

jobs:
  rebuild-check:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch cached binary
      uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      id: restore-cached-binary
      with:
        key: pony-binary-${{ runner.os }}
        path: |
          pony-api
          hash.txt

    - name: Checkout code
      if: ${{ !steps.restore-cached-binary.outputs.cache-hit }}
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: Check for source changes
      run: pony-api --check-binary >> $GITHUB_OUTPUT
      id: run-binary
      if: ${{ steps.restore-cached-binary.outputs.cache-hit }}

    - name: (Re)build binary
      if: ${{ !steps.restore-cached-binary.outputs.cache-hit || steps.run-binary.outputs.needs_cached == 'true' }}
      id: build
      working-directory: code
      run: |
        cargo build --release --bin pony-api
        cp target/release/pony-api ..
        echo "rebuilt=true" >> $GITHUB_OUTPUT

    - name: Cache binary
      uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      if: ${{ steps.build.outputs.rebuilt == 'true' }}
      with:
        key: pony-binary-${{ runner.os }}
        path: |
          pony-api
          hash.txt

    - name: Call JSON build workflow
      uses: ./.github/workflows/api.yaml
      with:
        rebuilt: ${{ steps.build.outputs.rebuilt == 'true' }}
