name: Deploy API

on:
  # workflow_call:
  #   inputs:
  #     rebuilt:
  #       required: true
  #       type: boolean
  push:
    branches:
    - disabled

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch cached binary
      uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      id: restore-cached-binary
      with:
        fail-on-cache-miss: true
        key: pony-binary-${{ runner.os }}
        path: |
          pony-api
          hash.txt

    - name: Rebuild JSON
      run: pony-api --rebuild-json
      if: ${{ inputs.rebuilt }}

    - name: Patch JSON
      run: pony-api --check-json
      if: ${{ !inputs.rebuilt }}

    - name: Deploy API
      run: |
        cd ./dist
        git diff --exit-code && exit 0
        git config --global user.name "Silk Rose"
        git config --global user.email "silkrose@love-tolerance.com"
        git remote set-url origin \
          "https://SilkRose:${{ secrets.GITHUB_TOKEN }}@github.com/SilkRose/${{ github.event.repository.name }}.git"
        git add -A
        hash=$(echo ${{ github.sha }} | head -c 7)
        git commit -m "Deploying to API from: $hash"
        git push
