name: Deploy API

on:
    push:
        branches:
            - mane

permissions:
    contents: write

jobs:
    rebuild-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

            - name: Build binary
              working-directory: code
              run: |
                  cargo build --release --bin pony-api
                  cp target/release/pony-api ../../

            - name: Build API
              run: cd ../ && ./pony-api

            - name: Deploy API
              run: |
                  cd ../dist
                  git diff --exit-code && exit 0
                  git config --global user.name "Silk Rose"
                  git config --global user.email "silkrose@love-tolerance.com"
                  git remote set-url origin \
                    "https://SilkRose:${{ secrets.GITHUB_TOKEN }}@github.com/SilkRose/${{ github.event.repository.name }}.git"
                  git add -A
                  hash=$(echo ${{ github.sha }} | head -c 7)
                  git commit -m "Deploying to API from: $hash"
                  git push
