name: Deploy API

on:
    push:
        branches:
            - mane

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Bun
              run: curl -fsSL https://bun.sh/install | bash

            - name: Download Files
              run: |
                  curl -s -O https://raw.githubusercontent.com/SilkRose/Pony/mane/code/api.ts
                  curl -s -O https://raw.githubusercontent.com/SilkRose/Pony/mane/code/package.json
                  curl -s -O https://raw.githubusercontent.com/SilkRose/Pony/mane/code/lib.ts

            - name: Install Dependencies
              run: ~/.bun/bin/bun install

            - name: Build API
              run: ~/.bun/bin/bun ./api.ts

            - name: Move Files
              run: |
                  cd ./pony-temp
                  git switch api
                  rm -rf ./api/ .nojekyll CNAME
                  mv ../dist/* ./ && mv ../dist/.nojekyll ./

            - name: Deploy API
              run: |
                  cd ./pony-temp
                  git config --global user.name "Silk Rose"
                  git config --global user.email "silkrose@love-tolerance.com"
                  git remote set-url origin \
                    "https://SilkRose:${{ secrets.GITHUB_TOKEN }}@github.com/SilkRose/${{ github.event.repository.name }}.git"
                  git add -A
                  hash=$(echo ${{ github.sha }} | head -c 7)
                  git commit -m "Deploying to API from: $hash"
                  git push
