name: Deploy API

on:
  push:
    branches:
      - mane

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: cd "./shell-scripts" && sh "./build-api.sh"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: api
          folder: shell-scripts/dist
