name: Deploy API

on:
    push:
        branches:
            - mane

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Build API
              run: |
                  curl -s https://raw.githubusercontent.com/SilkRose/Pony/mane/archive/code/pony-api.sh -o pony-api.sh
                  chmod +x ./pony-api.sh
                  ./pony-api.sh

            - name: Deploy API
              run: |
                  cd ./dist
                  git diff --exit-code && exit 0
                  git config --global user.name "Silk Rose"
                  git config --global user.email "silkrose@love-tolerance.com"
                  git remote set-url origin \
                    "https://SilkRose:${{ secrets.GITHUB_TOKEN }}@github.com/SilkRose/${{ github.event.repository.name }}.git"
                  git add -A
                  hash=$(echo ${{ github.sha }} | head -c 7)
                  git commit -m "Deploying to API from: $hash"
                  git push
