name: Deploy API

on:
    push:
        branches:
            - mane

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Bun
              run: curl -fsSL https://bun.sh/install | bash

            - name: Download Files
              run: |
                  curl -s -O https://raw.githubusercontent.com/SilkRose/Pony/main/code/api.ts
                  curl -s -O https://raw.githubusercontent.com/SilkRose/Pony/main/code/package.json
                  mkdir ./lib && cd ./lib
                  curl -s -O https://raw.githubusercontent.com/SilkRose/Pony/main/code/lib/pfetch.ts
                  curl -s -O https://raw.githubusercontent.com/SilkRose/Pony/main/code/lib/pexec.ts
                  curl -s -O https://raw.githubusercontent.com/SilkRose/Pony/main/code/lib/pfmt.ts
                  curl -s -O https://raw.githubusercontent.com/SilkRose/Pony/main/code/lib/pfs.ts
                  cd ..

            - name: Install Dependencies
              run: ~/.bun/bin/bun install

            - name: Build API
              run: ~/.bun/bin/bun ./api.ts

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: api
                  folder: dist
