name: Deploy API

on:
    push:
        branches:
            - mane

permissions:
    contents: write

jobs:
    rebuild-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              shell: bash
              run: |
                  git clone --quiet --branch api https://github.com/SilkRose/Pony.git ./dist &
                  git clone --quiet --branch cache https://github.com/SilkRose/Pony.git ./cache &
                  git clone --quiet --branch mane https://github.com/SilkRose/Pony.git ./pony-temp &
                  wait

            - name: Compare hashes
              id: check-hashes
              run: |
                  hashes=$(find ./pony-temp/code \
                    \( -name "*.rs" -o -wholename "./Cargo.toml" -o -wholename "./Cargo.lock" \) \
                    -exec sha256sum {} + | awk '{print $1}')
                  remote=$( [ -f ./cache/hash.txt ] && sha256sum ./cache/hash.txt | awk '{print $1}' || echo "")
                  local=$(echo "$hashes" | sha256sum | awk '{print $1}')
                  if [[ "$remote" != "$local" ]]; then echo "$local" > ./cache/hash.txt && echo "rebuild=true" >> $GITHUB_OUTPUT; fi

            - name: (Re)build binary
              if: ${{ steps.check-hashes.outputs.rebuild == 'true' }}
              id: build
              run: |
                  cd ./pony-temp/code
                  cargo build --release --bin pony-api
                  cp target/release/pony-api ../../cache
                  echo "rebuilt=true" >> $GITHUB_OUTPUT

            - name: Commit binary
              if: ${{ steps.build.outputs.rebuilt == 'true' }}
              run: |
                  cd ./cache
                  git config --global user.name "Silk Rose"
                  git config --global user.email "silkrose@love-tolerance.com"
                  git remote set-url origin \
                    "https://SilkRose:${{ secrets.GITHUB_TOKEN }}@github.com/SilkRose/Pony.git"
                  git add -A
                  hash=$(echo ${{ github.sha }} | head -c 7)
                  git commit --amend -m "Deploying to cache from: $hash"
                  git push --force

            - name: Move binary
              run: mv ./cache/pony-api .

            - name: Rebuild JSON
              run: ./pony-api --rebuild
              if: ${{ steps.build.outputs.rebuilt == 'true' }}

            - name: Patch JSON
              run: ./pony-api
              if: ${{ !steps.build.outputs.rebuilt == 'true' }}

            - name: Deploy API
              run: |
                  cd ./dist
                  git diff --exit-code && exit 0
                  git config --global user.name "Silk Rose"
                  git config --global user.email "silkrose@love-tolerance.com"
                  git remote set-url origin \
                    "https://SilkRose:${{ secrets.GITHUB_TOKEN }}@github.com/SilkRose/Pony.git"
                  git add -A
                  hash=$(echo ${{ github.sha }} | head -c 7)
                  git commit -m "Deploying to API from: $hash"
                  git push
