name: Deploy API

on:
    push:
        branches:
            - mane

permissions:
    contents: write

jobs:
    rebuild-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

            - name: Fetch cached hash
              uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
              id: restore-cached-hash
              with:
                  key: pony-binary-${{ runner.os }}-${{ hashFiles('**/*.rs','**/Cargo.toml','**/Cargo.lock') }}
                  path: |
                      hash.txt

            - name: (Re)build binary
              if: ${{ !steps.restore-cached-hash.outputs.cache-hit }}
              id: build
              working-directory: code
              run: |
                  cargo build --release --bin pony-api
                  cp target/release/pony-api ..
                  echo "rebuilt=true" >> $GITHUB_OUTPUT

            - name: Cache binary
              uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
              if: ${{ steps.build.outputs.rebuilt == 'true' }}
              with:
                  key: pony-binary-${{ runner.os }}-${{ hashFiles('**/*.rs','**/Cargo.toml','**/Cargo.lock') }}
                  path: |
                      pony-api
                      hash.txt

            - name: Rebuild JSON
              run: ./pony-api --rebuild
              if: ${{ !steps.restore-cached-hash.outputs.cache-hit }}

            - name: Patch JSON
              run: ./pony-api
              if: ${{ steps.restore-cached-hash.outputs.cache-hit }}

            - name: Deploy API
              run: |
                  cd ./dist
                  git diff --exit-code && exit 0
                  git config --global user.name "Silk Rose"
                  git config --global user.email "silkrose@love-tolerance.com"
                  git remote set-url origin \
                    "https://SilkRose:${{ secrets.GITHUB_TOKEN }}@github.com/SilkRose/${{ github.event.repository.name }}.git"
                  git add -A
                  hash=$(echo ${{ github.sha }} | head -c 7)
                  git commit -m "Deploying to API from: $hash"
                  git push
